language: java

sudo: false

install: true

jdk:
  - oraclejdk8

before_install:
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update
  - sudo apt-get install -y yarn

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.config/yarn/global/"
    - "$HOME/.yarn-cache/"

stages:
  - name: build
  - name: publish
    if: branch = master

jobs:
  include:
    - stage: build
      script:
        - ./gradlew clean build --console=plain
        - yarn
        - yarn test

    - stage: publish
      script:
        - ./gradlew clean build --console=plain
        - ./publish-all.sh
